server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lrsystem?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:com/jxd/lr/dao/mapping/*.xml
  type-aliases-package: com.jxd.lr.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
